/* tslint:disable */
/* eslint-disable */
/**
 * fastify-swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DenLightLightIdHsl
 */
export interface DenLightLightIdHsl {
    /**
     * 
     * @type {number}
     * @memberof DenLightLightIdHsl
     */
    h: number;
    /**
     * 
     * @type {number}
     * @memberof DenLightLightIdHsl
     */
    s: number;
    /**
     * 
     * @type {number}
     * @memberof DenLightLightIdHsl
     */
    l: number;
}

export function DenLightLightIdHslFromJSON(json: any): DenLightLightIdHsl {
    return DenLightLightIdHslFromJSONTyped(json, false);
}

export function DenLightLightIdHslFromJSONTyped(json: any, ignoreDiscriminator: boolean): DenLightLightIdHsl {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'h': json['h'],
        's': json['s'],
        'l': json['l'],
    };
}

export function DenLightLightIdHslToJSON(value?: DenLightLightIdHsl | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'h': value.h,
        's': value.s,
        'l': value.l,
    };
}


