/* tslint:disable */
/* eslint-disable */
/**
 * fastify-swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    DenLightLightIdHsl,
    DenLightLightIdHslFromJSON,
    DenLightLightIdHslFromJSONTyped,
    DenLightLightIdHslToJSON,
} from './';

/**
 * 
 * @export
 * @interface InlineResponse2002
 */
export interface InlineResponse2002 {
    /**
     * 
     * @type {DenLightLightIdHsl}
     * @memberof InlineResponse2002
     */
    hsl: DenLightLightIdHsl;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse2002
     */
    period?: number;
}

export function InlineResponse2002FromJSON(json: any): InlineResponse2002 {
    return InlineResponse2002FromJSONTyped(json, false);
}

export function InlineResponse2002FromJSONTyped(json: any, ignoreDiscriminator: boolean): InlineResponse2002 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'hsl': DenLightLightIdHslFromJSON(json['hsl']),
        'period': !exists(json, 'period') ? undefined : json['period'],
    };
}

export function InlineResponse2002ToJSON(value?: InlineResponse2002 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'hsl': DenLightLightIdHslToJSON(value.hsl),
        'period': value.period,
    };
}


