http:
  host: 0.0.0.0
  port: 3001
  corsOrigins:
    - http://localhost:3000
lights:
  - lightId: remembrall
    label: Remembrall
    kind: lifx
    ipv4: "192.168.0.110"
chromium:
  executablePath: /usr/bin/chromium-browser
  users:
    - userId: xxx
      google:
        email: xxx
        password: xxx
        findMyDeviceKey: "1"
